### ISSUE TITLE
当 sender 已指定时，允许搜索关键词为空以查询其发送的所有消息

### ISSUE THREAD

**Issue by rde9** [lilydjwg/luoxu-web#8]
例如：
1. 搜索 uid 为 313927976 用户的包含关键词 "google" 的消息
https://luoxu-web.vercel.app/#g=1476079359&q=google&sender=313927976 <=>
https://lab.lilydjwg.me/luoxu/search?g=1476079359&q=google&sender=313927976

2. 搜索 uid 为 313927976 用户的所有消息
? (error: 请输入搜索关键字) <=> https://lab.lilydjwg.me/luoxu/search?g=1476079359&sender=313927976

**Comment by lilydjwg** [comment]
其实一开始我是觉得 Telegram 里就可以按用户搜了，要这个功能没什么用。不过那个功能对已离开的用户就没法用，Matrix 那边的用户也用不了，就还是加上好了。
